name: Generar EPG XMLTV

on:
  schedule:
    - cron: '5 14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-commit-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Generar EPG
        run: python main.py

      - name: Subir EPG actualizado
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@github.com"
          git add -f epgpersonal.xml.gz
          git commit -m "EPG actualizado automáticamente - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No hay cambios que commitear"
          git push || echo "No hay nada que pushear"
