name: Run Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'config.json'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests -v

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          tests/__pycache__
          epg_generator.log
        retention-days: 5

    - name: Report test status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Todos los tests pasaron correctamente"
        else
          echo "❌ Algunos tests fallaron"
          exit 1
        fi
